;*****************************************************************
;*
;* - Description:  Code is part of the RC_Calibration.asm source
;*
;* - File:         memoryMap.inc
;* - AppNote:      AVR053 - Production calibration of the
;*                          RC oscillator
;*
;* - Author:       Atmel Corporation: http://www.atmel.com
;*                 Support email: avr@atmel.com
;*
;* $Name$
;* $Revision: 56 $
;* $RCSfile$
;* $Date: 2006-02-16 17:44:45 +0100 (to, 16 feb 2006) $
;*****************************************************************

.equ	ADDR_START		= 0x0000
.equ	ADDR_DEV_SPEC	= 0x0004
.equ	ADDR_MAIN		= 0x000A

.equ	EEPROM_ADDRESS	= 0x00
